InteriorDesign/InteriorDesign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from service import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('project/', include('project.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InteriorDesign/project/urls.py
from django.urls import path
from . import views

app_name = 'project'


urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:project_id>', views.project_detail, name='project_detail')
]

InteriorDesign/contact/models.py
from django.db import models

# Create your models here.

InteriorDesign/project/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=30)
    TYPE = (
            ('Office', 'Office'),
            ('Residential', 'Residential'),
            ('Commercial', 'Commercial')
        )
    type = models.CharField(max_length= 50, null=True, choices=TYPE)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('project:project_detail', kwargs = {
                'project_id':self.id
        })

InteriorDesign/service/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    image = models.ImageField(upload_to='images')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

class TeamMember(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title

InteriorDesign/project/forms.py
import django_filters
from .models import Project


class ProjectFilter(django_filters.FilterSet):
    class Meta:
        model = Project
        fields = ['type']

InteriorDesign/contact/views.py
from django.shortcuts import render

# Create your views here.
def contact(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        
        return render(request, 'contact.html',{'message_name':message_name})
    else:
        return render(request,'contact.html',{})

InteriorDesign/project/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project
from .forms import ProjectFilter

# Create your views here.
def all_projects(request):
    projects = Project.objects.all()
    filtered = ProjectFilter(request.GET, queryset=projects)
    projects = filtered.qs

    context = {
        'projects':projects,
        'filtered':filtered
    }
    return render(request, 'all_projects.html', context)

def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    context = {
        'project':project
    }
    return render(request, 'project_detail.html', context)

InteriorDesign/service/views.py
from django.shortcuts import render
from .models import Service, TeamMember

# Create your views here.
def index(request):
    services = Service.objects.all()
    teammembers = TeamMember.objects.all()
    context = {
        'services':services,
        'teammembers':teammembers
    }
    return render(request, 'index.html', context)

InteriorDesign/templates/all_projects.html
{% extends 'base.html' %}
{% load static %}

{% block content %} <br><br><br><br><br>

<div class="container-fluid">
  <p>Here you can search trough our projects</p>
<form method="get">
<h3>{{ filtered.form }}</h3>
<button class="btn btn-secondary" type="submit">Search</button>

</form>
</div> <br><br><br>
<div class="container-fluid">
<div class="row">

{% for project in projects %}
<div class="col-md-3">
<div class="card">
  <img class="card-img-top" src="{{ project.image.url }}" alt="Card image cap">
  <div class="card-body">
    <a href="{{ project.get_absolute_url }}"><h5 class="card-title">{{ project.title }}</h5></a>
    <p class="card-text">{{ project.description }}</p>
  </div>
</div>
</div>
{% endfor %}
</div>
</div>
{% endblock content %}

InteriorDesign/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% include 'head.html' %}
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

{% include 'nav.html' %}

{% block content %}
{% endblock content %}

{% include 'footer.html' %}
{% include 'scripts.html' %}


</body>

</html>

InteriorDesign/templates/contact.html
{% load static %}
<!-- Contact Section -->
<div id="contact">
  <div class="container">
    <div class="section-title text-center">
      <h2>Contact Us</h2>
      <hr>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit duis sed dapibus leonec.</p>
    </div>
    <div class="col-md-4">
      <h3>Contact Info</h3>
      <div class="contact-item"> <span>Address</span>
        <p>Panjiyar Toli ,Word No:-11<br>
          Rosera,Samastipur,Bihar Pin no:-848210</p>
      </div>
      <div class="contact-item"> <span>Email</span>
        <p>siddh2081@gmail.com</p>
      </div>
      <div class="contact-item"> <span>Phone</span>
        <p> +91 9709000166</p>
      </div>
    </div>
    <!-- Section Heading -->
    <div class="section-heading">
        <h2>Get in Touch</h2>
        <div class="line"></div>
    </div>
    <div class="col-md-8">
      <h3>Leave us a message</h3>
      <form name="sentMessage" id="contactForm" novalidate>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" name="message-name" id="name" class="form-control" placeholder="Name" required="required">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <input type="email" name="message-email" id="email" class="form-control" placeholder="Email" required="required">
              <p class="help-block text-danger"></p>
            </div>
          </div>
        </div>
        <div class="form-group">
          <textarea name="message" id="message" class="form-control" rows="4" placeholder="Message" required></textarea>
          <p class="help-block text-danger"></p>
        </div>
        <div id="success"></div>
        <button type="submit" class="btn btn-custom btn-lg">Send Message</button>
      </form>
    </div>
  </div>
</div>

InteriorDesign/templates/footer.html
{% load static %}
<div id="footer">
  <div class="container text-center">
    <div class="social">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-youtube"></i></a></li>
      </ul>
    </div>
    <div>
      <p>&copy; 2016 NEST. All rights reserved. Designed by <a href="http://www.templatewire.com" rel="nofollow">TemplateWire</a></p>
    </div>
  </div>
</div>

InteriorDesign/templates/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NEST</title>
<meta name="description" content="">
<meta name="author" content="">

<!-- Favicons
    ================================================== -->
<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
<link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-touch-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-touch-icon-114x114.png' %}">

<!-- Bootstrap -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">

<!-- Stylesheet
    ================================================== -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/nivo-lightbox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/default.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

InteriorDesign/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Header -->
<header id="header">
  <div class="intro">
    <div class="overlay">
      <div class="container">
        <div class="row">
          <div class="intro-text">
            <h1><strong>NEST</strong> <span>/</span> Interior Design Studio</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipiscing.</p>
            <a href="#about" class="btn btn-custom btn-lg page-scroll">Learn More</a> </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- About Section -->
<div id="about">
  <div class="container">
    <div class="section-title text-center center">
      <h2>Our Story</h2>
      <hr>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6 text-center"> <img src="{% static 'img/about.jpg' %}" class="img-responsive" alt=""> </div>
      <div class="col-xs-12 col-md-6">
        <div class="about-text">
          <h3>The Studio</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diam. Sed commodo nibh ante facilisis bibendum dolor feugiat at. Duis sed dapibus leo nec ornare diam commodo nibh.</p>
          <h3>How We Work</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diam. Sed commodo nibh ante facilisis bibendum dolor feugiat at. Duis sed dapibus leo nec ornare.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Services Section -->
<div id="services">
  <div class="container">
    <div class="col-md-10 col-md-offset-1 section-title text-center">
      <h2>Our Services</h2>
      <hr>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit duis sed dapibus leonec.</p>
    </div>
    <div class="row">
  {% for service in services %}

      <div class="col-xs-12 col-sm-4 service"> <img src="{{ service.image.url }}" class="img-responsive" alt="Project Title">
        <h3>{{ service.title }}</h3>
        <p>{{ service.description }}</p>
        {% if service.url %}
          <a href="{{ service.url }}">Check website</a>
        {% endif %}
      </div>
  {% endfor %}

    </div>
  </div>
</div>

<!-- Team Section -->
<div id="team" class="text-center">
  <div class="overlay">
    <div class="container">
      <div class="col-md-8 col-md-offset-2 section-title">
        <h2>Meet the Team</h2>
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit duis sed dapibus leonec.</p>
      </div>
      <div id="row">
        {% for member in teammembers %}
        <div class="col-md-3 col-sm-6 team">
          <div class="thumbnail"> <img src="{{ member.image.url }}" alt="..." class="team-img">
            <div class="caption">
              <h3>{{ member.title }}</h3>
              <p>{{ member.description }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

InteriorDesign/templates/nav.html
{% load static %}
<!-- Navigation
    ==========================================-->
<nav id="menu" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <a class="navbar-brand page-scroll" href="{% url 'index' %}">NEST</a> </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#about" class="page-scroll">About</a></li>
        <li><a href="#services" class="page-scroll">Services</a></li>
        <li><a href="{% url 'project:all_projects' %}" class="page-scroll">Projects</a></li>
        <li><a href="#team" class="page-scroll">Team</a></li>
        <li><a href="#contact" class="page-scroll">Contact</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
</nav>

InteriorDesign/templates/project_detail.html
{% extends 'base.html' %}

{% block content %} <br><br><br><br>


<div class="card">
  <img class="card-img-top" src="{{ project.image.url }}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{ project.title }}</h5>
    <p class="card-text">{{ project.description }}</p>
  </div>
</div>
<br><br>

{% endblock content %}

InteriorDesign/templates/scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery.1.11.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/SmoothScroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/nivo-lightbox.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.isotope.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jqBootstrapValidation.js' %}"></script>
<script type="text/javascript" src="{% static 'js/contact_me.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>